import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Constants for layout
const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 width in mm
const PRIMARY_COLOR = [217, 104, 70]; // #D96846
const SECONDARY_COLOR = [89, 98, 53]; // #596235
const TEXT_COLOR = [47, 48, 32]; // #2F3020
const LIGHT_BG = [245, 245, 245];

// Helper to add header
const addHeader = (doc, title, user = 'Admin') => {
    const today = new Date().toLocaleString();

    // Business Details (Top Left)
    doc.setFontSize(20);
    doc.setTextColor(...PRIMARY_COLOR);
    doc.setFont('helvetica', 'bold');
    doc.text("Ammachee Stock Management", MARGIN, 20);

    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.setFont('helvetica', 'normal');
    doc.text("123 Business Street, City, Country", MARGIN, 26);
    doc.text("Contact: +60 12-345 6789 | Email: info@ammachee.com", MARGIN, 31);

    // Report Title & Date (Top Right)
    doc.setFontSize(16);
    doc.setTextColor(...SECONDARY_COLOR);
    doc.setFont('helvetica', 'bold');
    doc.text(title, PAGE_WIDTH - MARGIN, 20, { align: 'right' });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${today}`, PAGE_WIDTH - MARGIN, 26, { align: 'right' });
    doc.text(`Generated by: ${user}`, PAGE_WIDTH - MARGIN, 31, { align: 'right' });

    // Divider Line
    doc.setDrawColor(200);
    doc.line(MARGIN, 35, PAGE_WIDTH - MARGIN, 35);

    return 45; // Return Y position for next content
};

// Helper to add footer
const addFooter = (doc) => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by Stock Management System", MARGIN, 285);
        doc.text("www.ammachee-stock.com", PAGE_WIDTH / 2, 285, { align: 'center' });
        doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 285, { align: 'right' });
    }
};

// Helper to add summary box
const addSummaryBox = (doc, startY, items) => {
    const boxHeight = 25;
    const boxWidth = (PAGE_WIDTH - (MARGIN * 2)) / items.length;

    items.forEach((item, index) => {
        const x = MARGIN + (index * boxWidth);

        // Box background
        doc.setFillColor(...(index % 2 === 0 ? LIGHT_BG : [255, 255, 255]));
        doc.rect(x, startY, boxWidth, boxHeight, 'F');

        // Border
        doc.setDrawColor(220);
        doc.rect(x, startY, boxWidth, boxHeight, 'S');

        // Label
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(item.label, x + (boxWidth / 2), startY + 8, { align: 'center' });

        // Value
        doc.setFontSize(12);
        doc.setTextColor(...TEXT_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text(item.value.toString(), x + (boxWidth / 2), startY + 18, { align: 'center' });
    });

    return startY + boxHeight + 10;
};

export const generateDailyReportPDF = (data, date, filterType) => {
    const doc = new jsPDF();
    let y = addHeader(doc, "Daily Sales Report");

    // Sub-header
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(`Report Date: ${date}`, MARGIN, y);
    if (filterType !== 'ALL') {
        doc.text(`Filter: ${filterType}`, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    }
    y += 10;

    // Summary Box
    y = addSummaryBox(doc, y, [
        { label: "Total Sales", value: `RM ${data.totalSales.toFixed(2)}` },
        { label: "Stock In Count", value: data.stockIn.length },
        { label: "Stock Out Count", value: data.stockOut.length }
    ]);

    // Transactions Table
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY_COLOR);
    doc.text("Transaction Details", MARGIN, y);
    y += 5;

    const tableRows = [...data.stockIn, ...data.stockOut].map(t => [
        t.type === 'IN' ? 'STOCK IN' : t.type === 'RETURN' ? 'RETURN' : 'STOCK OUT',
        t.platform || '-',
        t.productName,
        t.quantity,
        `RM ${(t.quantity * t.sellingPriceAtTime).toFixed(2)}`,
        t.notes || '-'
    ]);

    autoTable(doc, {
        startY: y,
        head: [['Type', 'Platform', 'Product', 'Qty', 'Value', 'Notes']],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: PRIMARY_COLOR },
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
            0: { fontStyle: 'bold' },
            3: { halign: 'right' }
        }
    });

    addFooter(doc);
    doc.save(`Daily_Report_${date}.pdf`);
};

export const generateMonthlyReportPDF = (data, month) => {
    const doc = new jsPDF();
    let y = addHeader(doc, "Monthly Sales Report");

    doc.setFontSize(12);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(`Report Month: ${month}`, MARGIN, y);
    y += 10;

    // Summary Box
    y = addSummaryBox(doc, y, [
        { label: "Total Revenue", value: `RM ${data.totalRevenue.toFixed(2)}` },
        { label: "Est. Profit", value: `RM ${data.profit.toFixed(2)}` },
        { label: "Units Sold", value: data.totalUnitsSold },
        { label: "Transactions", value: data.stockOut.length + data.stockIn.length }
    ]);

    // Top Products Table
    if (data.topProducts.length > 0) {
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Top 5 Products Sold", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Product Name', 'Quantity Sold']],
            body: data.topProducts.map(p => [p.name, p.quantity]),
            theme: 'striped',
            headStyles: { fillColor: SECONDARY_COLOR },
            margin: { left: MARGIN, right: PAGE_WIDTH / 2 } // Half width
        });

        y = doc.lastAutoTable.finalY + 15;
    }

    // Sales List
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY_COLOR);
    doc.text("Sales Transactions", MARGIN, y);
    y += 5;

    autoTable(doc, {
        startY: y,
        head: [['Date', 'Platform', 'Product', 'Qty', 'Total (RM)']],
        body: data.stockOut.map(t => [
            t.date,
            t.platform || '-',
            t.productName,
            t.quantity,
            (t.quantity * t.sellingPriceAtTime).toFixed(2)
        ]),
        theme: 'grid',
        headStyles: { fillColor: PRIMARY_COLOR },
        columnStyles: { 3: { halign: 'right' } }
    });

    const MARGIN = 15;
    const PAGE_WIDTH = 210; // A4 width in mm
    const PRIMARY_COLOR = [217, 104, 70]; // #D96846
    const SECONDARY_COLOR = [89, 98, 53]; // #596235
    const TEXT_COLOR = [47, 48, 32]; // #2F3020
    const LIGHT_BG = [245, 245, 245];

    // Helper to add header
    const addHeader = (doc, title, user = 'Admin') => {
        const today = new Date().toLocaleString();

        // Business Details (Top Left)
        doc.setFontSize(20);
        doc.setTextColor(...PRIMARY_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text("Ammachee Stock Management", MARGIN, 20);

        doc.setFontSize(10);
        doc.setTextColor(...TEXT_COLOR);
        doc.setFont('helvetica', 'normal');
        doc.text("123 Business Street, City, Country", MARGIN, 26);
        doc.text("Contact: +60 12-345 6789 | Email: info@ammachee.com", MARGIN, 31);

        // Report Title & Date (Top Right)
        doc.setFontSize(16);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text(title, PAGE_WIDTH - MARGIN, 20, { align: 'right' });

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.setFont('helvetica', 'normal');
        doc.text(`Generated: ${today}`, PAGE_WIDTH - MARGIN, 26, { align: 'right' });
        doc.text(`Generated by: ${user}`, PAGE_WIDTH - MARGIN, 31, { align: 'right' });

        // Divider Line
        doc.setDrawColor(200);
        doc.line(MARGIN, 35, PAGE_WIDTH - MARGIN, 35);

        return 45; // Return Y position for next content
    };

    // Helper to add footer
    const addFooter = (doc) => {
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text("Generated by Stock Management System", MARGIN, 285);
            doc.text("www.ammachee-stock.com", PAGE_WIDTH / 2, 285, { align: 'center' });
            doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 285, { align: 'right' });
        }
    };

    // Helper to add summary box
    const addSummaryBox = (doc, startY, items) => {
        const boxHeight = 25;
        const boxWidth = (PAGE_WIDTH - (MARGIN * 2)) / items.length;

        items.forEach((item, index) => {
            const x = MARGIN + (index * boxWidth);

            // Box background
            doc.setFillColor(...(index % 2 === 0 ? LIGHT_BG : [255, 255, 255]));
            doc.rect(x, startY, boxWidth, boxHeight, 'F');

            // Border
            doc.setDrawColor(220);
            doc.rect(x, startY, boxWidth, boxHeight, 'S');

            // Label
            doc.setFontSize(9);
            doc.setTextColor(100);
            doc.text(item.label, x + (boxWidth / 2), startY + 8, { align: 'center' });

            // Value
            doc.setFontSize(12);
            doc.setTextColor(...TEXT_COLOR);
            doc.setFont('helvetica', 'bold');
            doc.text(item.value.toString(), x + (boxWidth / 2), startY + 18, { align: 'center' });
        });

        return startY + boxHeight + 10;
    };

    export const generateDailyReportPDF = (data, date, filterType) => {
        const doc = new jsPDF();
        let y = addHeader(doc, "Daily Sales Report");

        // Sub-header
        doc.setFontSize(12);
        doc.setTextColor(...TEXT_COLOR);
        doc.text(`Report Date: ${date}`, MARGIN, y);
        if (filterType !== 'ALL') {
            doc.text(`Filter: ${filterType}`, PAGE_WIDTH - MARGIN, y, { align: 'right' });
        }
        y += 10;

        // Summary Box
        y = addSummaryBox(doc, y, [
            { label: "Total Sales", value: `RM ${data.totalSales.toFixed(2)}` },
            { label: "Stock In Count", value: data.stockIn.length },
            { label: "Stock Out Count", value: data.stockOut.length }
        ]);

        // Transactions Table
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Transaction Details", MARGIN, y);
        y += 5;

        const tableRows = [...data.stockIn, ...data.stockOut].map(t => [
            t.type === 'IN' ? 'STOCK IN' : t.type === 'RETURN' ? 'RETURN' : 'STOCK OUT',
            t.platform || '-',
            t.productName,
            t.quantity,
            `RM ${(t.quantity * t.sellingPriceAtTime).toFixed(2)}`,
            t.notes || '-'
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Type', 'Platform', 'Product', 'Qty', 'Value', 'Notes']],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: PRIMARY_COLOR },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                0: { fontStyle: 'bold' },
                3: { halign: 'right' }
            }
        });

        addFooter(doc);
        doc.save(`Daily_Report_${date}.pdf`);
    };

    export const generateMonthlyReportPDF = (data, month) => {
        const doc = new jsPDF();
        let y = addHeader(doc, "Monthly Sales Report");

        doc.setFontSize(12);
        doc.setTextColor(...TEXT_COLOR);
        doc.text(`Report Month: ${month}`, MARGIN, y);
        y += 10;

        // Summary Box
        y = addSummaryBox(doc, y, [
            { label: "Total Revenue", value: `RM ${data.totalRevenue.toFixed(2)}` },
            { label: "Est. Profit", value: `RM ${data.profit.toFixed(2)}` },
            { label: "Units Sold", value: data.totalUnitsSold },
            { label: "Transactions", value: data.stockOut.length + data.stockIn.length }
        ]);

        // Top Products Table
        if (data.topProducts.length > 0) {
            doc.setFontSize(12);
            doc.setTextColor(...SECONDARY_COLOR);
            doc.text("Top 5 Products Sold", MARGIN, y);
            y += 5;

            autoTable(doc, {
                startY: y,
                head: [['Product Name', 'Quantity Sold']],
                body: data.topProducts.map(p => [p.name, p.quantity]),
                theme: 'striped',
                headStyles: { fillColor: SECONDARY_COLOR },
                margin: { left: MARGIN, right: PAGE_WIDTH / 2 } // Half width
            });

            y = doc.lastAutoTable.finalY + 15;
        }

        // Sales List
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Sales Transactions", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Date', 'Platform', 'Product', 'Qty', 'Total (RM)']],
            body: data.stockOut.map(t => [
                t.date,
                t.platform || '-',
                t.productName,
                t.quantity,
                (t.quantity * t.sellingPriceAtTime).toFixed(2)
            ]),
            theme: 'grid',
            headStyles: { fillColor: PRIMARY_COLOR },
            columnStyles: { 3: { halign: 'right' } }
        });

        // If there's space, add Stock In, else new page handled by autoTable
        y = doc.lastAutoTable.finalY + 15;

        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Stock In Transactions", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Date', 'Type', 'Product', 'Qty', 'Notes']],
            body: data.stockIn.map(t => [
                t.date,
                t.type === 'IN' ? 'STOCK IN' : 'RETURN',
                t.productName,
                t.quantity,
                t.notes || '-'
            ]),
            theme: 'grid',
            headStyles: { fillColor: [100, 100, 100] }
        });

        addFooter(doc);
        doc.save(`Monthly_Report_${month}.pdf`);
    };

    export const generateProductReportPDF = (data, product) => {
        const doc = new jsPDF();
        let y = addHeader(doc, "Product Performance Report");

        doc.setFontSize(12);
        doc.setTextColor(...TEXT_COLOR);
        doc.text(`Product: ${product.name}`, MARGIN, y);
        doc.setFontSize(10);
        doc.text(`Category: ${product.category} | Price: RM ${product.sellingPrice}`, MARGIN, y + 6);
        y += 15;

        // Summary Box
        y = addSummaryBox(doc, y, [
            { label: "Current Stock", value: product.currentStock },
            { label: "Total Stock In", value: data.totalIn },
            { label: "Total Stock Out", value: data.totalOut }
        ]);

        // Transaction History
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Transaction History", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Date', 'Type', 'Platform', 'Qty', 'Notes']],
            body: data.transactions.map(t => [
                t.date,
                t.type === 'IN' ? 'STOCK IN' : t.type === 'RETURN' ? 'RETURN' : 'STOCK OUT',
                t.platform || '-',
                t.quantity,
                t.notes || '-'
            ]),
            theme: 'grid',
            headStyles: { fillColor: PRIMARY_COLOR },
            didParseCell: (data) => {
                if (data.section === 'body' && data.column.index === 1) {
                    if (data.cell.raw === 'STOCK IN') {
                        data.cell.styles.textColor = [46, 125, 50]; // Green
                    } else if (data.cell.raw === 'RETURN') {
                        data.cell.styles.textColor = [217, 119, 6]; // Orange/Amber
                    } else {
                        data.cell.styles.textColor = [198, 40, 40]; // Red
                    }
                }
            }
        });

        addFooter(doc);
        doc.save(`Product_Report_${product.name.replace(/\s+/g, '_')}.pdf`);
    };
