import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Constants for layout
const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 width in mm
const PRIMARY_COLOR = [217, 104, 70]; // #D96846
const SECONDARY_COLOR = [89, 98, 53]; // #596235
const TEXT_COLOR = [47, 48, 32]; // #2F3020
const LIGHT_BG = [245, 245, 245];

// Helper to add header
const addHeader = (doc, title, user = 'Admin') => {
    const today = new Date().toLocaleString();

    // Business Details (Top Left)
    doc.setFontSize(20);
    doc.setTextColor(...PRIMARY_COLOR);
    doc.setFont('helvetica', 'bold');
    doc.text("Ammachee Stock Management", MARGIN, 20);

    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.setFont('helvetica', 'normal');
    doc.text("123 Business Street, City, Country", MARGIN, 26);
    doc.text("Contact: +60 12-345 6789 | Email: info@ammachee.com", MARGIN, 31);

    // Report Title & Date (Top Right)
    doc.setFontSize(16);
    doc.setTextColor(...SECONDARY_COLOR);
    doc.setFont('helvetica', 'bold');
    doc.text(title, PAGE_WIDTH - MARGIN, 20, { align: 'right' });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${today}`, PAGE_WIDTH - MARGIN, 26, { align: 'right' });
    doc.text(`Generated by: ${user}`, PAGE_WIDTH - MARGIN, 31, { align: 'right' });

    // Divider Line
    doc.setDrawColor(200);
    doc.line(MARGIN, 35, PAGE_WIDTH - MARGIN, 35);

    return 45; // Return Y position for next content
};

// Helper to add footer
const addFooter = (doc) => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by Stock Management System", MARGIN, 285);
        doc.text("www.ammachee-stock.com", PAGE_WIDTH / 2, 285, { align: 'center' });
        doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 285, { align: 'right' });
    }
};

// Helper to add summary box
const addSummaryBox = (doc, startY, items) => {
    const boxHeight = 25;
    const boxWidth = (PAGE_WIDTH - (MARGIN * 2)) / items.length;

    items.forEach((item, index) => {
        const x = MARGIN + (index * boxWidth);

        // Box background
        doc.setFillColor(...(index % 2 === 0 ? LIGHT_BG : [255, 255, 255]));
        doc.rect(x, startY, boxWidth, boxHeight, 'F');

        // Border
        doc.setDrawColor(220);
        doc.rect(x, startY, boxWidth, boxHeight, 'S');

        // Label
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(item.label, x + (boxWidth / 2), startY + 8, { align: 'center' });

        // Value
        doc.setFontSize(12);
        doc.setTextColor(...TEXT_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text(item.value.toString(), x + (boxWidth / 2), startY + 18, { align: 'center' });
    });

    return startY + boxHeight + 10;
};

// Helper to aggregate data
const aggregateData = (data, type) => {
    const aggregated = {};

    data.forEach(item => {
        let key;
        if (type === 'IN') {
            key = item.productName;
        } else {
            key = `${item.platform || '-'}_${item.productName}`;
        }

        if (!aggregated[key]) {
            aggregated[key] = {
                ...item,
                quantity: 0,
                totalValue: 0,
                notes: []
            };
        }

        aggregated[key].quantity += item.quantity;

        let value = 0;
        if (type === 'OUT') {
            value = item.quantity * (item.sellingPriceAtTime || 0);
        } else if (type === 'IN') {
            value = item.quantity * (item.purchasePriceAtTime || 0);
        }

        aggregated[key].totalValue += value;

        if (item.notes) {
            aggregated[key].notes.push(item.notes);
        }
    });

    return Object.values(aggregated).map(item => ({
        ...item,
        notes: [...new Set(item.notes)].join(', ')
    }));
};

export const generateDailyReportPDF = (data, date, filterType, platformFilter = 'All Platforms') => {
    const doc = new jsPDF();
    let y = addHeader(doc, "Daily Sales Report");

    // Sub-header
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(`Report Date: ${date}`, MARGIN, y);

    let filterText = '';
    if (filterType !== 'ALL') filterText += `Type: ${filterType} `;
    if (platformFilter !== 'All Platforms') filterText += `Platform: ${platformFilter}`;

    if (filterText) {
        doc.text(filterText, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    }
    y += 10;

    // Summary Box
    y = addSummaryBox(doc, y, [
        { label: "Total Sales", value: `RM ${data.totalSales.toFixed(2)}` },
        { label: "Stock In Count", value: data.stockIn.length },
        { label: "Stock Out Count", value: data.stockOut.length }
    ]);

    const stockOutItems = aggregateData(data.stockOut, 'OUT');
    const stockInItems = aggregateData(data.stockIn.filter(t => t.type === 'IN'), 'IN');
    const returnItems = aggregateData(data.stockIn.filter(t => t.type === 'RETURN'), 'RETURN');

    // Table 1: Stock Out Details
    if (stockOutItems.length > 0) {
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Stock Out Details", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Platform', 'Product', 'Qty', 'Value', 'Notes']],
            body: stockOutItems.map(t => [
                t.platform || '-',
                t.productName,
                t.quantity,
                `RM ${t.totalValue.toFixed(2)}`,
                t.notes || '-'
            ]),
            theme: 'grid',
            headStyles: { fillColor: PRIMARY_COLOR },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                0: { fontStyle: 'bold' },
                3: { halign: 'right' }
            }
        });
        y = doc.lastAutoTable.finalY + 15;
    }

    // Table 2: Stock In Details
    if (stockInItems.length > 0) {
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Stock In Details", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Product', 'Qty', 'Value', 'Notes']],
            body: stockInItems.map(t => [
                t.productName,
                t.quantity,
                `RM ${t.totalValue.toFixed(2)}`,
                t.notes || '-'
            ]),
            theme: 'grid',
            headStyles: { fillColor: [46, 125, 50] }, // Green for Stock In
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                2: { halign: 'right' }
            }
        });
        y = doc.lastAutoTable.finalY + 15;
    }

    // Table 3: Returned Products
    if (returnItems.length > 0) {
        doc.setFontSize(12);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.text("Returned Products", MARGIN, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Platform', 'Product', 'Qty', 'Notes']],
            body: returnItems.map(t => [
                t.platform || '-',
                t.productName,
                t.quantity,
                t.notes || '-'
            ]),
            theme: 'grid',
            headStyles: { fillColor: [217, 119, 6] }, // Orange for Returns
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                0: { fontStyle: 'bold' }
            }
        });
    }

    addFooter(doc);
};

export const generateMonthlyReportPDF = (data, month, platformFilter = 'All Platforms') => {
    const doc = new jsPDF();

    // --- Header ---
    const [year, monthNum] = month.split('-');
    const formattedDate = `${monthNum}//${year}`;

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.text("MONTH :", MARGIN, 20);
    const textWidth = doc.getTextWidth("MONTH :");
    doc.line(MARGIN, 21, MARGIN + textWidth, 21);
    doc.text(` ${formattedDate}`, MARGIN + textWidth, 20);

    let y = 40;

    // Helper for aggregation
    const aggregateByProduct = (transactions) => {
        const map = {};
        transactions.forEach(t => {
            if (!map[t.productName]) {
                map[t.productName] = {
                    productName: t.productName,
                    quantity: 0,
                    platforms: new Set()
                };
            }
            map[t.productName].quantity += t.quantity;
            if (t.platform) map[t.productName].platforms.add(t.platform);
        });
        return Object.values(map).map(item => ({
            ...item,
            platforms: Array.from(item.platforms).join(', ') || '-'
        })).sort((a, b) => a.productName.localeCompare(b.productName));
    };

    // --- Table 1: Total separate all product sales ---
    doc.setFontSize(12);
    doc.text("Total separate all product sales", MARGIN, y);
    y += 10;

    const salesData = aggregateByProduct(data.stockOut);

    autoTable(doc, {
        startY: y,
        head: [['Product Name', 'Total Sales', 'Platform']],
        body: salesData.map(item => [
            item.productName,
            item.quantity,
            item.platforms
        ]),
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 5, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [255, 255, 255], textColor: [0, 0, 0], fontStyle: 'bold' },
        columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 40, halign: 'center' },
            2: { cellWidth: 60 }
        }
    });

    y = doc.lastAutoTable.finalY + 20;

    // --- Table 2: Total separate all product stock in ---
    doc.text("Total separate all product stock in", MARGIN, y);
    y += 10;

    const stockInData = aggregateByProduct(data.stockIn.filter(t => t.type === 'IN'));

    autoTable(doc, {
        startY: y,
        head: [['Product Name', 'Total Stock In', 'Platform']],
        body: stockInData.map(item => [
            item.productName,
            item.quantity,
            item.platforms
        ]),
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 5, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [255, 255, 255], textColor: [0, 0, 0], fontStyle: 'bold' },
        columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 40, halign: 'center' },
            2: { cellWidth: 60 }
        }
    });

    y = doc.lastAutoTable.finalY + 20;

    // --- Table 3: Total separate all product Return ---
    doc.text("Total separate all product Return", MARGIN, y);
    y += 10;

    const returnData = aggregateByProduct(data.stockIn.filter(t => t.type === 'RETURN'));

    autoTable(doc, {
        startY: y,
        head: [['Product Name', 'Total Return', 'Platform']],
        body: returnData.map(item => [
            item.productName,
            item.quantity,
            item.platforms
        ]),
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 5, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [255, 255, 255], textColor: [0, 0, 0], fontStyle: 'bold' },
        columnStyles: {
            0: { cellWidth: 80 },
            1: { cellWidth: 40, halign: 'center' },
            2: { cellWidth: 60 }
        }
    });

    addFooter(doc);
    doc.save(`Monthly_Report_${month}.pdf`);
};

export const generateProductReportPDF = (data, product, platformFilter = 'All Platforms') => {
    const doc = new jsPDF();
    let y = addHeader(doc, "Product Performance Report");

    doc.setFontSize(12);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(`Product: ${product.name}`, MARGIN, y);
    doc.setFontSize(10);
    doc.text(`Category: ${product.category} | Price: RM ${product.sellingPrice}`, MARGIN, y + 6);

    if (platformFilter !== 'All Platforms') {
        doc.text(`Platform: ${platformFilter}`, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    }
    y += 15;

    // Summary Box
    y = addSummaryBox(doc, y, [
        { label: "Current Stock", value: product.currentStock },
        { label: "Total Stock In", value: data.totalIn },
        { label: "Total Stock Out", value: data.totalOut }
    ]);

    // Transaction History
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY_COLOR);
    doc.text("Transaction History", MARGIN, y);
    y += 5;

    autoTable(doc, {
        startY: y,
        head: [['Date', 'Type', 'Platform', 'Qty', 'Notes']],
        body: data.transactions.map(t => [
            t.date,
            t.type === 'IN' ? 'STOCK IN' : t.type === 'RETURN' ? 'RETURN' : 'STOCK OUT',
            t.platform || '-',
            t.quantity,
            t.notes || '-'
        ]),
        theme: 'grid',
        headStyles: { fillColor: PRIMARY_COLOR },
        didParseCell: (data) => {
            if (data.section === 'body' && data.column.index === 1) {
                if (data.cell.raw === 'STOCK IN') {
                    data.cell.styles.textColor = [46, 125, 50]; // Green
                } else if (data.cell.raw === 'RETURN') {
                    data.cell.styles.textColor = [217, 119, 6]; // Orange/Amber
                } else {
                    data.cell.styles.textColor = [198, 40, 40]; // Red
                }
            }
        }
    });

    addFooter(doc);
    doc.save(`Product_Report_${product.name.replace(/\s+/g, '_')}.pdf`);
};
