import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Constants for layout
const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 width in mm
const PRIMARY_COLOR = [217, 104, 70]; // #D96846 (Brand Orange)
const SECONDARY_COLOR = [47, 48, 32]; // #2F3020 (Dark Accent)
const TEXT_COLOR = [47, 48, 32];
const LIGHT_BG = [252, 247, 245]; // Very light orange/grey tint
const BOX_BG = [255, 255, 255]; // White for boxes

// Helper to add header
const addHeader = (doc, title, date) => {
    // Top Bar Background
    doc.setFillColor(...SECONDARY_COLOR);
    doc.rect(0, 0, PAGE_WIDTH, 45, 'F');

    // Company Name
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text("Ammachee Stock Management", MARGIN, 20);

    // Report Title
    doc.setFontSize(14);
    doc.setTextColor(217, 104, 70); // Orange text
    doc.setFont('helvetica', 'bold');
    doc.text(title.toUpperCase(), MARGIN, 32);

    // Date
    doc.setFontSize(11);
    doc.setTextColor(200, 200, 200);
    doc.setFont('helvetica', 'normal');
    doc.text(date, PAGE_WIDTH - MARGIN, 20, { align: 'right' });

    return 60; // Return Y position for next content
};

// Helper to add footer
const addFooter = (doc) => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by Daily Stock System", MARGIN, 285);
        doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 285, { align: 'right' });
    }
};

// Helper to add section title
const addSectionTitle = (doc, title, y) => {
    doc.setFontSize(13);
    doc.setTextColor(...SECONDARY_COLOR);
    doc.setFont('helvetica', 'bold');
    doc.text(title.toUpperCase(), MARGIN, y);
    // Underline
    doc.setDrawColor(...PRIMARY_COLOR);
    doc.setLineWidth(1);
    doc.line(MARGIN, y + 2, MARGIN + 20, y + 2);
    return y + 10;
};



export const generateDailyReportPDF = (data, date, filterType, platformFilter = 'All Platforms', intelligentNotes = {}, products = [], accountFilter = 'All Accounts') => {
    const doc = new jsPDF();
    let title = "Daily Stock Report";
    if (accountFilter !== 'All Accounts') {
        title += ` - ${accountFilter}`;
    }
    let y = addHeader(doc, title, date);

    // 1. Total Summary
    y = addSectionTitle(doc, "1. Total Summary", y);

    const summaryItems = [
        { label: "Total Sale", value: `${data.totalSales.toFixed(0)} units` }, // Using quantity as units based on request "X units"
        { label: "Total Stock-In", value: `${data.totalStockIn} units` },
        { label: "Total Returns", value: `${data.totalReturns} units` }
    ];

    const boxWidth = (PAGE_WIDTH - (MARGIN * 2)) / 3;
    const boxHeight = 24;

    summaryItems.forEach((item, index) => {
        const x = MARGIN + (index * boxWidth);

        // Card Background (White with shadow-like border)
        doc.setDrawColor(220, 220, 220);
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(x + 2, y, boxWidth - 4, boxHeight, 3, 3, 'FD');

        // Label
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
        doc.setFont('helvetica', 'bold');
        doc.text(item.label.toUpperCase(), x + 6, y + 8);

        // Value
        doc.setFontSize(14);
        doc.setTextColor(...PRIMARY_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text(item.value, x + 6, y + 18);
    });

    y += boxHeight + 10;

    // 2. Sales Breakdown
    if (data.stockOut.length > 0) {
        y = addSectionTitle(doc, "2. Sales Breakdown", y);

        const salesBody = data.stockOut.map(t => [
            t.productName,
            t.quantity,
            `RM ${t.sellingPriceAtTime ? t.sellingPriceAtTime.toFixed(2) : '0.00'}`,
            t.platform || '-',
            t.receiverName || '-',
            `RM ${(t.quantity * (t.sellingPriceAtTime || 0)).toFixed(2)}`
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Product Name', 'Quantity Sold', 'Price', 'Platform', 'Receiver Name', 'Total Amount']],
            body: salesBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: LIGHT_BG },
            styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 },
            columnStyles: {
                0: { cellWidth: 50 },
                5: { halign: 'right' }
            }
        });
        y = doc.lastAutoTable.finalY + 10;
    }

    // 3. Stock-In Breakdown
    const stockInOnly = data.stockIn.filter(t => t.type === 'IN');
    if (stockInOnly.length > 0) {
        y = addSectionTitle(doc, "3. Stock-In Breakdown", y);

        const stockInBody = stockInOnly.map(t => [
            t.productName,
            t.quantity,
            t.supplier || '-',
            t.date
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Product Name', 'Stock-In Qty', 'Supplier', 'Date']],
            body: stockInBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: LIGHT_BG },
            styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 }
        });
        y = doc.lastAutoTable.finalY + 10;
    }

    // 4. Return Breakdown
    const returnsOnly = data.stockIn.filter(t => t.type === 'RETURN');
    if (returnsOnly.length > 0) {
        y = addSectionTitle(doc, "4. Return Breakdown", y);

        const returnBody = returnsOnly.map(t => [
            t.productName,
            t.quantity,
            t.platform || '-',
            t.returnReason || '-',
            t.notes || '-'
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Product Name', 'Return Qty', 'Platform', 'Return Reason', 'Notes']],
            body: returnBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: LIGHT_BG },
            styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 }
        });
        y = doc.lastAutoTable.finalY + 10;
    }

    // 5. Intelligent Notes
    // Check if we need a new page
    if (y > 200) {
        doc.addPage();
        y = 20;
    }

    y = addSectionTitle(doc, "5. Intelligent Notes", y);

    const notesData = [
        [`Top-selling platform: ${intelligentNotes.topPlatform || '-'}`],
        [`Platform with lowest sales: ${intelligentNotes.lowestPlatform || '-'}`],
        [`Products with highest return rate: ${intelligentNotes.highestReturnProduct || '-'}`],
        [`Recommended actions: ${intelligentNotes.recommendation || '-'}`]
    ];

    autoTable(doc, {
        startY: y,
        body: notesData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: 'italic' } }
    });

    y = doc.lastAutoTable.finalY + 10;

    // 6. Remaining Stock Breakdown
    // Check if we need a new page
    if (y > 200) {
        doc.addPage();
        y = 20;
    }

    y = addSectionTitle(doc, "6. Remaining Stock Breakdown", y);

    if (products && products.length > 0) {
        const stockBody = products.map(p => [
            p.name,
            p.category,
            `${p.currentStock} units`
        ]).sort((a, b) => a[0].localeCompare(b[0])); // Sort by product name

        autoTable(doc, {
            startY: y,
            head: [['Product Name', 'Category', 'Available Stock']],
            body: stockBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                2: { halign: 'right', fontStyle: 'bold' }
            }
        });
    } else {
        doc.setFontSize(10);
        doc.setTextColor(...TEXT_COLOR);
        doc.setFont('helvetica', 'italic');
        doc.text("No product data available.", MARGIN, y + 5);
    }

    addFooter(doc);
    doc.save(`Daily_Report_${date}.pdf`);
};

export const generateMonthlyReportPDF = (data, month, platformFilter = 'All Platforms', products = [], accountFilter = 'All Accounts') => {
    const doc = new jsPDF();

    // --- Header ---
    const [year, monthNum] = month.split('-');
    const dateObj = new Date(year, monthNum - 1);
    const monthName = dateObj.toLocaleString('default', { month: 'long' });
    const formattedDate = `${monthName} ${year}`;

    let title = "Monthly Stock Report";
    if (accountFilter !== 'All Accounts') {
        title += ` - ${accountFilter}`;
    }

    let y = addHeader(doc, title, formattedDate);

    // 1. Monthly Summary
    y = addSectionTitle(doc, "1. Monthly Summary", y);

    const summaryItems = [
        { label: "Total Sales", value: `${data.totalUnitsSold} units` },
        { label: "Total Sales Value", value: `RM ${data.totalRevenue.toFixed(2)}` },
        { label: "Total Stock-In", value: `${data.totalStockIn} units` },
        { label: "Total Returns", value: `${data.totalReturns} units` },
        { label: "Top Platform", value: data.monthlyInsights?.highestGrowthPlatform || '-' },
        { label: "Most Returned", value: data.monthlyInsights?.unusualReturns?.split(',')[0] || '-' }
    ];

    const boxWidth = (PAGE_WIDTH - (MARGIN * 2)) / 3;
    const boxHeight = 24;

    summaryItems.forEach((item, index) => {
        const row = Math.floor(index / 3);
        const col = index % 3;
        const x = MARGIN + (col * boxWidth);
        const currentY = y + (row * (boxHeight + 5));

        // Card (Rounded + Border)
        doc.setDrawColor(220, 220, 220);
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(x + 2, currentY, boxWidth - 4, boxHeight, 3, 3, 'FD');

        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
        doc.setFont('helvetica', 'bold');
        doc.text(item.label.toUpperCase(), x + 6, currentY + 8);

        doc.setFontSize(11);
        doc.setTextColor(...PRIMARY_COLOR); // Orange numbers
        doc.setFont('helvetica', 'bold');
        const valueText = doc.splitTextToSize(item.value, boxWidth - 10);
        doc.text(valueText, x + 6, currentY + 18);
    });

    y += (Math.ceil(summaryItems.length / 3) * (boxHeight + 5)) + 10;

    // 2. Sales Breakdown (Separate Table per Platform)
    y = addSectionTitle(doc, "2. Sales Breakdown", y);

    // Group sales by Platform
    const salesByPlatform = {};
    data.stockOut.forEach(t => {
        const platform = t.platform || 'Unknown';
        if (!salesByPlatform[platform]) salesByPlatform[platform] = [];
        salesByPlatform[platform].push(t);
    });

    Object.entries(salesByPlatform).forEach(([platform, transactions]) => {
        // Check page break
        if (y > 220) { doc.addPage(); y = 20; }

        // Platform Sub-header
        doc.setFontSize(11);
        doc.setTextColor(...SECONDARY_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text(`Platform: ${platform}`, MARGIN, y);
        y += 6;

        // Aggregate by Product within this Platform
        const productMap = {};
        transactions.forEach(t => {
            if (!productMap[t.productName]) {
                productMap[t.productName] = {
                    productName: t.productName,
                    quantity: 0,
                    totalAmount: 0,
                    totalAmount: 0,
                    price: t.sellingPriceAtTime || 0,
                    dates: [],
                    receiverNames: new Set()
                };
            }
            productMap[t.productName].quantity += t.quantity;
            productMap[t.productName].totalAmount += (t.quantity * (t.sellingPriceAtTime || 0));
            productMap[t.productName].dates.push(new Date(t.date));
            if (t.receiverName) productMap[t.productName].receiverNames.add(t.receiverName);
        });

        const tableBody = Object.values(productMap).map(item => {
            const minDate = new Date(Math.min(...item.dates)).getDate();
            const maxDate = new Date(Math.max(...item.dates)).getDate();
            const dateRange = minDate === maxDate ? `${minDate}` : `${minDate}-${maxDate}`;
            const receiverNamesStr = item.receiverNames && item.receiverNames.size > 0
                ? Array.from(item.receiverNames).join(', ')
                : '-';

            // For NVS SAMA SAMA, use Receiver Name in the last column. For others, use Date Range.
            const lastColumnValue = platform === 'NVS SAMA SAMA' ? receiverNamesStr : dateRange;

            return [
                item.productName,
                item.quantity,
                `RM ${item.price.toFixed(2)}`,
                `RM ${item.totalAmount.toFixed(2)}`,
                lastColumnValue
            ];
        }).sort((a, b) => a[0].localeCompare(b[0]));

        const tableHeaders = platform === 'NVS SAMA SAMA'
            ? [['Product Name', 'Qty Sold', 'Price', 'Total Amount', 'Receiver Name']]
            : [['Product Name', 'Qty Sold', 'Price', 'Total Amount', 'Date Range']];

        autoTable(doc, {
            startY: y,
            head: tableHeaders,
            body: tableBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: LIGHT_BG },
            styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 },
            columnStyles: {
                3: { halign: 'right' },
                4: { halign: 'center' }
            }
        });

        y = doc.lastAutoTable.finalY + 10;
    });

    // 3. Stock-In Breakdown
    // Check page break
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, "3. Stock-In Breakdown", y);

    const stockInOnly = data.stockIn.filter(t => t.type === 'IN');
    const stockInBody = stockInOnly.map(t => [
        t.productName,
        t.quantity,
        t.supplier || '-',
        t.date
    ]);

    autoTable(doc, {
        startY: y,
        head: [['Product Name', 'Stock-In Qty', 'Supplier', 'Date']],
        body: stockInBody,
        theme: 'grid',
        headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: LIGHT_BG },
        styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 }
    });

    y = doc.lastAutoTable.finalY + 10;

    // 4. Return Breakdown
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, "4. Return Breakdown", y);

    const returnsOnly = data.stockIn.filter(t => t.type === 'RETURN');
    const returnBody = returnsOnly.map(t => [
        t.productName,
        t.quantity,
        t.platform || '-',
        t.returnReason || '-',
        t.notes || '-'
    ]);

    autoTable(doc, {
        startY: y,
        head: [['Product Name', 'Return Qty', 'Platform', 'Return Reason', 'Notes']],
        body: returnBody,
        theme: 'grid',
        headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: LIGHT_BG },
        styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 }
    });

    y = doc.lastAutoTable.finalY + 10;

    // 5. Platform Performance Overview
    if (y > 200) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, "5. Platform Performance Overview", y);

    if (data.platformPerformance) {
        const platformBody = data.platformPerformance.map(p => [
            p.platform,
            p.sales,
            `${p.percentage.toFixed(1)}%`,
            p.returns,
            p.net
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Platform', 'Total Sales', '% Contribution', 'Total Returns', 'Net Performance']],
            body: platformBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: LIGHT_BG },
            styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 },
            columnStyles: {
                2: { halign: 'center' },
                4: { halign: 'right', fontStyle: 'bold' }
            }
        });
        y = doc.lastAutoTable.finalY + 10;
    }

    // 6. Auto Insights
    if (y > 200) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, "6. Auto Insights", y);

    const insights = data.monthlyInsights || {};
    const notesData = [
        [`Best-selling product: ${insights.bestSellingProduct || '-'}`],
        [`Week with highest sales: ${insights.highestSalesWeek || '-'}`],
        [`Platform with highest growth: ${insights.highestGrowthPlatform || '-'}`],
        [`Products with unusual returns: ${insights.unusualReturns || '-'}`],
        [`Recommendations: ${insights.recommendations || '-'}`]
    ];

    autoTable(doc, {
        startY: y,
        body: notesData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: 'italic' } }
    });

    // 7. Closing Stock Report (Next Month Opening)
    if (y > 200) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, "7. Closing Stock Report (Next Month Opening)", y);

    if (data.closingStock && data.closingStock.length > 0) {
        const closingStockBody = data.closingStock.map(p => [
            p.name,
            p.category,
            `${p.closingStock} units`
        ]).sort((a, b) => a[0].localeCompare(b[0]));

        autoTable(doc, {
            startY: y,
            head: [['Product Name', 'Category', 'Closing Stock (Next Month Opening)']],
            body: closingStockBody,
            theme: 'grid',
            headStyles: { fillColor: SECONDARY_COLOR, textColor: [255, 255, 255], fontStyle: 'bold' },
            alternateRowStyles: { fillColor: LIGHT_BG },
            styles: { fontSize: 9, cellPadding: 4, lineColor: [230, 230, 230], lineWidth: 0.1 },
            columnStyles: {
                2: { halign: 'right', fontStyle: 'bold' }
            }
        });
    } else {
        doc.setFontSize(10);
        doc.setTextColor(...TEXT_COLOR);
        doc.setFont('helvetica', 'italic');
        doc.text("No closing stock data available.", MARGIN, y + 5);
    }

    addFooter(doc);
    doc.save(`Monthly_Report_${month}.pdf`);
};

export const generateProductReportPDF = (data, product, platformFilter = 'All Platforms') => {
    const doc = new jsPDF();
    let y = addHeader(doc, "Product Performance Report", new Date().toLocaleDateString());

    // Product Header Box
    doc.setDrawColor(217, 104, 70); // Primary Orange
    doc.setFillColor(252, 247, 245); // Light BG
    doc.roundedRect(MARGIN, y, PAGE_WIDTH - (MARGIN * 2), 25, 3, 3, 'FD');

    doc.setFontSize(12);
    doc.setTextColor(47, 48, 32); // Secondary Dark
    doc.setFont('helvetica', 'bold');
    doc.text(`PRODUCT: ${product.name.toUpperCase()}`, MARGIN + 5, y + 8);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Category: ${product.category}`, MARGIN + 5, y + 16);
    doc.text(`Current Price: RM ${product.sellingPrice}`, MARGIN + 80, y + 16);

    if (platformFilter !== 'All Platforms') {
        doc.text(`Filter: ${platformFilter}`, MARGIN + 5, y + 22);
    }
    y += 35;

    // Helper for aggregation by platform
    const aggregateByPlatform = (transactions) => {
        const map = {};
        transactions.forEach(t => {
            const platform = t.platform || '-';
            if (!map[platform]) {
                map[platform] = {
                    platform: platform,
                    quantity: 0
                };
            }
            map[platform].quantity += t.quantity;
        });
        return Object.values(map).sort((a, b) => a.platform.localeCompare(b.platform));
    };

    // --- Table 1: Total Sales (Stock Out) ---
    doc.setFontSize(12);
    doc.setTextColor(217, 104, 70); // Orange
    doc.text("Total Sales", MARGIN, y);
    y += 5;

    const salesData = aggregateByPlatform(data.stockOut);

    autoTable(doc, {
        startY: y,
        head: [['Platform', 'Total Sales']],
        body: salesData.map(item => [
            item.platform,
            item.quantity
        ]),
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 5, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [47, 48, 32], textColor: [255, 255, 255], fontStyle: 'bold' }, // Dark
        alternateRowStyles: { fillColor: [252, 247, 245] },
        columnStyles: {
            0: { cellWidth: 100 },
            1: { cellWidth: 50, halign: 'center' }
        }
    });

    y = doc.lastAutoTable.finalY + 15;

    // --- Table 2: Total Stock In ---
    doc.setTextColor(76, 175, 80); // Green
    doc.text("Total Stock In", MARGIN, y);
    y += 5;

    const stockInData = aggregateByPlatform(data.stockIn.filter(t => t.type === 'IN'));

    autoTable(doc, {
        startY: y,
        head: [['Platform', 'Total Stock In']],
        body: stockInData.map(item => [
            item.platform,
            item.quantity
        ]),
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 5, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [76, 175, 80], textColor: [255, 255, 255], fontStyle: 'bold' }, // Green
        alternateRowStyles: { fillColor: [252, 247, 245] },
        columnStyles: {
            0: { cellWidth: 100 },
            1: { cellWidth: 50, halign: 'center' }
        }
    });

    y = doc.lastAutoTable.finalY + 15;

    // --- Table 3: Total Return ---
    doc.setTextColor(244, 67, 54); // Red
    doc.text("Total Return", MARGIN, y);
    y += 5;

    const returnData = aggregateByPlatform(data.stockIn.filter(t => t.type === 'RETURN'));

    autoTable(doc, {
        startY: y,
        head: [['Platform', 'Total Return']],
        body: returnData.map(item => [
            item.platform,
            item.quantity
        ]),
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 5, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [244, 67, 54], textColor: [255, 255, 255], fontStyle: 'bold' }, // Red
        alternateRowStyles: { fillColor: [252, 247, 245] },
        columnStyles: {
            0: { cellWidth: 100 },
            1: { cellWidth: 50, halign: 'center' }
        }
    });

    addFooter(doc);
    doc.save(`Product_Report_${product.name.replace(/\s+/g, '_')}.pdf`);
};
